In [268]:
## 데이터 조회
import sqlite3

conn = sqlite3.connect('./db.sqlite3')
cur = conn.cursor()

query =  '''SELECT * FROM main_chicken '''

cur.execute(query)

rows = cur.fetchall()
for row in rows:
    print(row)
    
cur.close()
conn.close()

(1537, '경기도', '2021-03-19 00:00', 423, '치킨')
(1538, '경기도', '2021-03-19 01:00', 208, '치킨')
(1539, '경기도', '2021-03-19 02:00', 73, '치킨')
(1540, '경기도', '2021-03-19 03:00', 25, '치킨')
(1541, '경기도', '2021-03-19 04:00', 18, '치킨')
(1542, '경기도', '2021-03-19 05:00', 15, '치킨')
(1543, '경기도', '2021-03-19 06:00', 12, '치킨')
(1544, '경기도', '2021-03-19 07:00', 11, '치킨')
(1545, '경기도', '2021-03-19 08:00', 11, '치킨')
(1546, '경기도', '2021-03-19 09:00', 12, '치킨')
(1547, '경기도', '2021-03-19 10:00', 19, '치킨')
(1548, '경기도', '2021-03-19 11:00', 139, '치킨')
(1549, '경기도', '2021-03-19 12:00', 322, '치킨')
(1550, '경기도', '2021-03-19 13:00', 343, '치킨')
(1551, '경기도', '2021-03-19 14:00', 324, '치킨')
(1552, '경기도', '2021-03-19 15:00', 375, '치킨')
(1553, '경기도', '2021-03-19 16:00', 563, '치킨')
(1554, '경기도', '2021-03-19 17:00', 1140, '치킨')
(1555, '경기도', '2021-03-19 18:00', 1998, '치킨')
(1556, '경기도', '2021-03-19 19:00', 2293, '치킨')
(1557, '경기도', '2021-03-19 20:00', 1834, '치킨')
(1558, '경기도', '2021-03-19 21:00', 1567, '치킨')
(1559, '경기도', '2021-03-19 22:00', 1272, '치킨')
(1560, '경기도', '2021-03-19 23:00', 797, '치킨')
(1561, '경기도', '2021-03-20 00:00', 382, '치킨')
(1562, '경기도', '2021-03-20 01:00', 193, '치킨')
(1563, '경기도', '2021-03-20 02:00', 76, '치킨')
(1564, '경기도', '2021-03-20 03:00', 24, '치킨')
(1565, '경기도', '2021-03-20 04:00', 18, '치킨')
(1566, '경기도', '2021-03-20 05:00', 15, '치킨')
(1567, '경기도', '2021-03-20 06:00', 13, '치킨')
(1568, '경기도', '2021-03-20 07:00', 11, '치킨')
(1569, '경기도', '2021-03-20 08:00', 11, '치킨')
(1570, '경기도', '2021-03-20 09:00', 14, '치킨')
(1571, '경기도', '2021-03-20 10:00', 20, '치킨')
(1572, '경기도', '2021-03-20 11:00', 153, '치킨')
(1573, '경기도', '2021-03-20 12:00', 389, '치킨')
(1574, '경기도', '2021-03-20 13:00', 390, '치킨')
(1575, '경기도', '2021-03-20 14:00', 395, '치킨')
(1576, '경기도', '2021-03-20 15:00', 471, '치킨')
(1577, '경기도', '2021-03-20 16:00', 681, '치킨')
(1578, '경기도', '2021-03-20 17:00', 1390, '치킨')
(1579, '경기도', '2021-03-20 18:00', 2387, '치킨')
(1580, '경기도', '2021-03-20 19:00', 2494, '치킨')
(1581, '경기도', '2021-03-20 20:00', 2058, '치킨')
(1582, '경기도', '2021-03-20 21:00', 1722, '치킨')
(1583, '경기도', '2021-03-20 22:00', 1260, '치킨')
(1584, '경기도', '2021-03-20 23:00', 840, '치킨')
(1585, '경기도', '2021-03-21 00:00', 439, '치킨')
(1586, '경기도', '2021-03-21 01:00', 216, '치킨')
(1587, '경기도', '2021-03-21 02:00', 80, '치킨')
(1588, '경기도', '2021-03-21 03:00', 25, '치킨')
(1589, '경기도', '2021-03-21 04:00', 18, '치킨')
(1590, '경기도', '2021-03-21 05:00', 16, '치킨')
(1591, '경기도', '2021-03-21 06:00', 13, '치킨')
(1592, '경기도', '2021-03-21 07:00', 11, '치킨')
(1593, '경기도', '2021-03-21 08:00', 11, '치킨')
(1594, '경기도', '2021-03-21 09:00', 14, '치킨')
(1595, '경기도', '2021-03-21 10:00', 20, '치킨')
(1596, '경기도', '2021-03-21 11:00', 150, '치킨')
(1597, '경기도', '2021-03-21 12:00', 327, '치킨')
(1598, '경기도', '2021-03-21 13:00', 357, '치킨')
(1599, '경기도', '2021-03-21 14:00', 367, '치킨')
(1600, '경기도', '2021-03-21 15:00', 436, '치킨')
(1601, '경기도', '2021-03-21 16:00', 657, '치킨')
(1602, '경기도', '2021-03-21 17:00', 1372, '치킨')
(1603, '경기도', '2021-03-21 18:00', 2407, '치킨')
(1604, '경기도', '2021-03-21 19:00', 2391, '치킨')
(1605, '경기도', '2021-03-21 20:00', 2011, '치킨')
(1606, '경기도', '2021-03-21 21:00', 1644, '치킨')
(1607, '경기도', '2021-03-21 22:00', 1297, '치킨')
(1608, '경기도', '2021-03-21 23:00', 874, '치킨')
(1609, '경기도', '2021-03-22 00:00', 247, '치킨')
(1610, '경기도', '2021-03-22 01:00', 130, '치킨')
(1611, '경기도', '2021-03-22 02:00', 47, '치킨')
(1612, '경기도', '2021-03-22 03:00', 15, '치킨')
(1613, '경기도', '2021-03-22 04:00', 11, '치킨')
(1614, '경기도', '2021-03-22 05:00', 9, '치킨')
(1615, '경기도', '2021-03-22 06:00', 8, '치킨')
(1616, '경기도', '2021-03-22 07:00', 6, '치킨')
(1617, '경기도', '2021-03-22 08:00', 6, '치킨')
(1618, '경기도', '2021-03-22 09:00', 7, '치킨')
(1619, '경기도', '2021-03-22 10:00', 11, '치킨')
(1620, '경기도', '2021-03-22 11:00', 82, '치킨')
(1621, '경기도', '2021-03-22 12:00', 186, '치킨')
(1622, '경기도', '2021-03-22 13:00', 212, '치킨')
(1623, '경기도', '2021-03-22 14:00', 214, '치킨')
(1624, '경기도', '2021-03-22 15:00', 245, '치킨')
(1625, '경기도', '2021-03-22 16:00', 369, '치킨')
(1626, '경기도', '2021-03-22 17:00', 748, '치킨')
(1627, '경기도', '2021-03-22 18:00', 1307, '치킨')
(1628, '경기도', '2021-03-22 19:00', 1366, '치킨')
(1629, '경기도', '2021-03-22 20:00', 1094, '치킨')
(1630, '경기도', '2021-03-22 21:00', 903, '치킨')
(1631, '경기도', '2021-03-22 22:00', 730, '치킨')
(1632, '경기도', '2021-03-22 23:00', 483, '치킨')
(1633, '경기도', '2021-03-23 00:00', 300, '치킨')
(1634, '경기도', '2021-03-23 01:00', 161, '치킨')
(1635, '경기도', '2021-03-23 02:00', 57, '치킨')
(1636, '경기도', '2021-03-23 03:00', 18, '치킨')
(1637, '경기도', '2021-03-23 04:00', 13, '치킨')
(1638, '경기도', '2021-03-23 05:00', 12, '치킨')
(1639, '경기도', '2021-03-23 06:00', 10, '치킨')
(1640, '경기도', '2021-03-23 07:00', 8, '치킨')
(1641, '경기도', '2021-03-23 08:00', 8, '치킨')
(1642, '경기도', '2021-03-23 09:00', 9, '치킨')
(1643, '경기도', '2021-03-23 10:00', 13, '치킨')
(1644, '경기도', '2021-03-23 11:00', 95, '치킨')
(1645, '경기도', '2021-03-23 12:00', 218, '치킨')
(1646, '경기도', '2021-03-23 13:00', 231, '치킨')
(1647, '경기도', '2021-03-23 14:00', 233, '치킨')
(1648, '경기도', '2021-03-23 15:00', 267, '치킨')
(1649, '경기도', '2021-03-23 16:00', 399, '치킨')
(1650, '경기도', '2021-03-23 17:00', 818, '치킨')
(1651, '경기도', '2021-03-23 18:00', 1440, '치킨')
(1652, '경기도', '2021-03-23 19:00', 1561, '치킨')
(1653, '경기도', '2021-03-23 20:00', 1280, '치킨')
(1654, '경기도', '2021-03-23 21:00', 1062, '치킨')
(1655, '경기도', '2021-03-23 22:00', 864, '치킨')
(1656, '경기도', '2021-03-23 23:00', 573, '치킨')
(1657, '경기도', '2021-03-24 00:00', 285, '치킨')
(1658, '경기도', '2021-03-24 01:00', 149, '치킨')
(1659, '경기도', '2021-03-24 02:00', 55, '치킨')
(1660, '경기도', '2021-03-24 03:00', 18, '치킨')
(1661, '경기도', '2021-03-24 04:00', 13, '치킨')
(1662, '경기도', '2021-03-24 05:00', 11, '치킨')
(1663, '경기도', '2021-03-24 06:00', 10, '치킨')
(1664, '경기도', '2021-03-24 07:00', 8, '치킨')
(1665, '경기도', '2021-03-24 08:00', 8, '치킨')
(1666, '경기도', '2021-03-24 09:00', 10, '치킨')
(1667, '경기도', '2021-03-24 10:00', 14, '치킨')
(1668, '경기도', '2021-03-24 11:00', 98, '치킨')
(1669, '경기도', '2021-03-24 12:00', 232, '치킨')
(1670, '경기도', '2021-03-24 13:00', 244, '치킨')
(1671, '경기도', '2021-03-24 14:00', 238, '치킨')
(1672, '경기도', '2021-03-24 15:00', 276, '치킨')
(1673, '경기도', '2021-03-24 16:00', 410, '치킨')
(1674, '경기도', '2021-03-24 17:00', 843, '치킨')
(1675, '경기도', '2021-03-24 18:00', 1514, '치킨')
(1676, '경기도', '2021-03-24 19:00', 1658, '치킨')
(1677, '경기도', '2021-03-24 20:00', 1360, '치킨')
(1678, '경기도', '2021-03-24 21:00', 1131, '치킨')
(1679, '경기도', '2021-03-24 22:00', 897, '치킨')
(1680, '경기도', '2021-03-24 23:00', 618, '치킨')
(1681, '경기도', '2021-03-25 00:00', 384, '치킨')
(1682, '경기도', '2021-03-25 01:00', 203, '치킨')
(1683, '경기도', '2021-03-25 02:00', 76, '치킨')
(1684, '경기도', '2021-03-25 03:00', 24, '치킨')
(1685, '경기도', '2021-03-25 04:00', 17, '치킨')
(1686, '경기도', '2021-03-25 05:00', 15, '치킨')
(1687, '경기도', '2021-03-25 06:00', 12, '치킨')
(1688, '경기도', '2021-03-25 07:00', 10, '치킨')
(1689, '경기도', '2021-03-25 08:00', 10, '치킨')
(1690, '경기도', '2021-03-25 09:00', 12, '치킨')
(1691, '경기도', '2021-03-25 10:00', 17, '치킨')
(1692, '경기도', '2021-03-25 11:00', 122, '치킨')
(1693, '경기도', '2021-03-25 12:00', 287, '치킨')
(1694, '경기도', '2021-03-25 13:00', 301, '치킨')
(1695, '경기도', '2021-03-25 14:00', 300, '치킨')
(1696, '경기도', '2021-03-25 15:00', 335, '치킨')
(1697, '경기도', '2021-03-25 16:00', 509, '치킨')
(1698, '경기도', '2021-03-25 17:00', 1045, '치킨')
(1699, '경기도', '2021-03-25 18:00', 1877, '치킨')
(1700, '경기도', '2021-03-25 19:00', 2033, '치킨')
(1701, '경기도', '2021-03-25 20:00', 1791, '치킨')
(1702, '경기도', '2021-03-25 21:00', 1396, '치킨')
(1703, '경기도', '2021-03-25 22:00', 1190, '치킨')
(1704, '경기도', '2021-03-25 23:00', 768, '치킨')
(1705, '경기도', '2021-03-26 00:00', 312, '치킨')
(1706, '경기도', '2021-03-26 01:00', 165, '치킨')
(1707, '경기도', '2021-03-26 02:00', 62, '치킨')
(1708, '경기도', '2021-03-26 03:00', 19, '치킨')
(1709, '경기도', '2021-03-26 04:00', 14, '치킨')
(1710, '경기도', '2021-03-26 05:00', 12, '치킨')
(1711, '경기도', '2021-03-26 06:00', 10, '치킨')
(1712, '경기도', '2021-03-26 07:00', 8, '치킨')
(1713, '경기도', '2021-03-26 08:00', 8, '치킨')
(1714, '경기도', '2021-03-26 09:00', 10, '치킨')
(1715, '경기도', '2021-03-26 10:00', 14, '치킨')
(1716, '경기도', '2021-03-26 11:00', 100, '치킨')
(1717, '경기도', '2021-03-26 12:00', 220, '치킨')
(1718, '경기도', '2021-03-26 13:00', 252, '치킨')
(1719, '경기도', '2021-03-26 14:00', 239, '치킨')
(1720, '경기도', '2021-03-26 15:00', 274, '치킨')
(1721, '경기도', '2021-03-26 16:00', 405, '치킨')
(1722, '경기도', '2021-03-26 17:00', 835, '치킨')
(1723, '경기도', '2021-03-26 18:00', 1475, '치킨')
(1724, '경기도', '2021-03-26 19:00', 1564, '치킨')
(1725, '경기도', '2021-03-26 20:00', 1325, '치킨')
(1726, '경기도', '2021-03-26 21:00', 1059, '치킨')
(1727, '경기도', '2021-03-26 22:00', 882, '치킨')
(1728, '경기도', '2021-03-26 23:00', 577, '치킨')
(1729, '경기도', '2021-03-27 00:00', 397, '치킨')
(1730, '경기도', '2021-03-27 01:00', 188, '치킨')
(1731, '경기도', '2021-03-27 02:00', 75, '치킨')
(1732, '경기도', '2021-03-27 03:00', 24, '치킨')
(1733, '경기도', '2021-03-27 04:00', 17, '치킨')
(1734, '경기도', '2021-03-27 05:00', 15, '치킨')
(1735, '경기도', '2021-03-27 06:00', 13, '치킨')
(1736, '경기도', '2021-03-27 07:00', 11, '치킨')
(1737, '경기도', '2021-03-27 08:00', 11, '치킨')
(1738, '경기도', '2021-03-27 09:00', 12, '치킨')
(1739, '경기도', '2021-03-27 10:00', 18, '치킨')
(1740, '경기도', '2021-03-27 11:00', 134, '치킨')
(1741, '경기도', '2021-03-27 12:00', 328, '치킨')
(1742, '경기도', '2021-03-27 13:00', 357, '치킨')
(1743, '경기도', '2021-03-27 14:00', 372, '치킨')
(1744, '경기도', '2021-03-27 15:00', 465, '치킨')
(1745, '경기도', '2021-03-27 16:00', 661, '치킨')
(1746, '경기도', '2021-03-27 17:00', 1346, '치킨')
(1747, '경기도', '2021-03-27 18:00', 2675, '치킨')
(1748, '경기도', '2021-03-27 19:00', 2476, '치킨')
(1749, '경기도', '2021-03-27 20:00', 1991, '치킨')
(1750, '경기도', '2021-03-27 21:00', 1786, '치킨')
(1751, '경기도', '2021-03-27 22:00', 1303, '치킨')
(1752, '경기도', '2021-03-27 23:00', 853, '치킨')
(1753, '경기도', '2021-03-28 00:00', 350, '치킨')
(1754, '경기도', '2021-03-28 01:00', 167, '치킨')
(1755, '경기도', '2021-03-28 02:00', 61, '치킨')
(1756, '경기도', '2021-03-28 03:00', 21, '치킨')
(1757, '경기도', '2021-03-28 04:00', 14, '치킨')
(1758, '경기도', '2021-03-28 05:00', 13, '치킨')
(1759, '경기도', '2021-03-28 06:00', 10, '치킨')
(1760, '경기도', '2021-03-28 07:00', 9, '치킨')
(1761, '경기도', '2021-03-28 08:00', 9, '치킨')
(1762, '경기도', '2021-03-28 09:00', 11, '치킨')
(1763, '경기도', '2021-03-28 10:00', 16, '치킨')
(1764, '경기도', '2021-03-28 11:00', 120, '치킨')
(1765, '경기도', '2021-03-28 12:00', 292, '치킨')
(1766, '경기도', '2021-03-28 13:00', 304, '치킨')
(1767, '경기도', '2021-03-28 14:00', 309, '치킨')
(1768, '경기도', '2021-03-28 15:00', 352, '치킨')
(1769, '경기도', '2021-03-28 16:00', 537, '치킨')
(1770, '경기도', '2021-03-28 17:00', 1091, '치킨')
(1771, '경기도', '2021-03-28 18:00', 1872, '치킨')
(1772, '경기도', '2021-03-28 19:00', 1983, '치킨')
(1773, '경기도', '2021-03-28 20:00', 1588, '치킨')
(1774, '경기도', '2021-03-28 21:00', 1290, '치킨')
(1775, '경기도', '2021-03-28 22:00', 1027, '치킨')
(1776, '경기도', '2021-03-28 23:00', 645, '치킨')
(1777, '경기도', '2021-03-29 00:00', 208, '치킨')
(1778, '경기도', '2021-03-29 01:00', 127, '치킨')
(1779, '경기도', '2021-03-29 02:00', 44, '치킨')
(1780, '경기도', '2021-03-29 03:00', 14, '치킨')
(1781, '경기도', '2021-03-29 04:00', 8, '치킨')
(1782, '경기도', '2021-03-29 05:00', 7, '치킨')
(1783, '경기도', '2021-03-29 06:00', 5, '치킨')
(1784, '경기도', '2021-03-29 07:00', 4, '치킨')
(1785, '경기도', '2021-03-29 08:00', 4, '치킨')
(1786, '경기도', '2021-03-29 09:00', 5, '치킨')
(1787, '경기도', '2021-03-29 10:00', 7, '치킨')
(1788, '경기도', '2021-03-29 11:00', 53, '치킨')
(1789, '경기도', '2021-03-29 12:00', 139, '치킨')
(1790, '경기도', '2021-03-29 13:00', 158, '치킨')
(1791, '경기도', '2021-03-29 14:00', 162, '치킨')
(1792, '경기도', '2021-03-29 15:00', 206, '치킨')
(1793, '경기도', '2021-03-29 16:00', 297, '치킨')
(1794, '경기도', '2021-03-29 17:00', 620, '치킨')
(1795, '경기도', '2021-03-29 18:00', 1094, '치킨')
(1796, '경기도', '2021-03-29 19:00', 1190, '치킨')
(1797, '경기도', '2021-03-29 20:00', 920, '치킨')
(1798, '경기도', '2021-03-29 21:00', 732, '치킨')
(1799, '경기도', '2021-03-29 22:00', 586, '치킨')
(1800, '경기도', '2021-03-29 23:00', 385, '치킨')
(1801, '경기도', '2021-03-30 00:00', 203, '치킨')
(1802, '경기도', '2021-03-30 01:00', 88, '치킨')
(1803, '경기도', '2021-03-30 02:00', 32, '치킨')
(1804, '경기도', '2021-03-30 03:00', 11, '치킨')
(1805, '경기도', '2021-03-30 04:00', 8, '치킨')
(1806, '경기도', '2021-03-30 05:00', 7, '치킨')
(1807, '경기도', '2021-03-30 06:00', 6, '치킨')
(1808, '경기도', '2021-03-30 07:00', 5, '치킨')
(1809, '경기도', '2021-03-30 08:00', 5, '치킨')
(1810, '경기도', '2021-03-30 09:00', 5, '치킨')
(1811, '경기도', '2021-03-30 10:00', 8, '치킨')
(1812, '경기도', '2021-03-30 11:00', 60, '치킨')
(1813, '경기도', '2021-03-30 12:00', 143, '치킨')
(1814, '경기도', '2021-03-30 13:00', 157, '치킨')
(1815, '경기도', '2021-03-30 14:00', 158, '치킨')
(1816, '경기도', '2021-03-30 15:00', 181, '치킨')
(1817, '경기도', '2021-03-30 16:00', 274, '치킨')
(1818, '경기도', '2021-03-30 17:00', 560, '치킨')
(1819, '경기도', '2021-03-30 18:00', 1005, '치킨')
(1820, '경기도', '2021-03-30 19:00', 1082, '치킨')
(1821, '경기도', '2021-03-30 20:00', 894, '치킨')
(1822, '경기도', '2021-03-30 21:00', 738, '치킨')
(1823, '경기도', '2021-03-30 22:00', 602, '치킨')
(1824, '경기도', '2021-03-30 23:00', 403, '치킨')
(1825, '경기도', '2021-03-31 00:00', 265, '치킨')
(1826, '경기도', '2021-03-31 01:00', 140, '치킨')
(1827, '경기도', '2021-03-31 02:00', 52, '치킨')
(1828, '경기도', '2021-03-31 03:00', 17, '치킨')
(1829, '경기도', '2021-03-31 04:00', 12, '치킨')
(1830, '경기도', '2021-03-31 05:00', 11, '치킨')
(1831, '경기도', '2021-03-31 06:00', 9, '치킨')
(1832, '경기도', '2021-03-31 07:00', 7, '치킨')
(1833, '경기도', '2021-03-31 08:00', 7, '치킨')
(1834, '경기도', '2021-03-31 09:00', 8, '치킨')
(1835, '경기도', '2021-03-31 10:00', 12, '치킨')
(1836, '경기도', '2021-03-31 11:00', 85, '치킨')
(1837, '경기도', '2021-03-31 12:00', 189, '치킨')
(1838, '경기도', '2021-03-31 13:00', 207, '치킨')
(1839, '경기도', '2021-03-31 14:00', 204, '치킨')
(1840, '경기도', '2021-03-31 15:00', 231, '치킨')
(1841, '경기도', '2021-03-31 16:00', 354, '치킨')
(1842, '경기도', '2021-03-31 17:00', 725, '치킨')
(1843, '경기도', '2021-03-31 18:00', 1281, '치킨')
(1844, '경기도', '2021-03-31 19:00', 1341, '치킨')
(1845, '경기도', '2021-03-31 20:00', 1157, '치킨')
(1846, '경기도', '2021-03-31 21:00', 968, '치킨')
(1847, '경기도', '2021-03-31 22:00', 797, '치킨')
(1848, '경기도', '2021-03-31 23:00', 534, '치킨')
(1849, '경기도', '2021-04-01 00:00', 277, '치킨')
(1850, '경기도', '2021-04-01 01:00', 142, '치킨')
(1851, '경기도', '2021-04-01 02:00', 54, '치킨')
(1852, '경기도', '2021-04-01 03:00', 17, '치킨')
(1853, '경기도', '2021-04-01 04:00', 12, '치킨')
(1854, '경기도', '2021-04-01 05:00', 11, '치킨')
(1855, '경기도', '2021-04-01 06:00', 9, '치킨')
(1856, '경기도', '2021-04-01 07:00', 7, '치킨')
(1857, '경기도', '2021-04-01 08:00', 7, '치킨')
(1858, '경기도', '2021-04-01 09:00', 8, '치킨')
(1859, '경기도', '2021-04-01 10:00', 12, '치킨')
(1860, '경기도', '2021-04-01 11:00', 88, '치킨')
(1861, '경기도', '2021-04-01 12:00', 202, '치킨')
(1862, '경기도', '2021-04-01 13:00', 214, '치킨')
(1863, '경기도', '2021-04-01 14:00', 214, '치킨')
(1864, '경기도', '2021-04-01 15:00', 248, '치킨')
(1865, '경기도', '2021-04-01 16:00', 368, '치킨')
(1866, '경기도', '2021-04-01 17:00', 749, '치킨')
(1867, '경기도', '2021-04-01 18:00', 1362, '치킨')
(1868, '경기도', '2021-04-01 19:00', 1487, '치킨')
(1869, '경기도', '2021-04-01 20:00', 1168, '치킨')
(1870, '경기도', '2021-04-01 21:00', 1016, '치킨')
(1871, '경기도', '2021-04-01 22:00', 793, '치킨')
(1872, '경기도', '2021-04-01 23:00', 538, '치킨')
(1873, '경기도', '2021-04-02 00:00', 287, '치킨')
(1874, '경기도', '2021-04-02 01:00', 157, '치킨')
(1875, '경기도', '2021-04-02 02:00', 56, '치킨')
(1876, '경기도', '2021-04-02 03:00', 18, '치킨')
(1877, '경기도', '2021-04-02 04:00', 13, '치킨')
(1878, '경기도', '2021-04-02 05:00', 11, '치킨')
(1879, '경기도', '2021-04-02 06:00', 9, '치킨')
(1880, '경기도', '2021-04-02 07:00', 8, '치킨')
(1881, '경기도', '2021-04-02 08:00', 8, '치킨')
(1882, '경기도', '2021-04-02 09:00', 9, '치킨')
(1883, '경기도', '2021-04-02 10:00', 13, '치킨')
(1884, '경기도', '2021-04-02 11:00', 96, '치킨')
(1885, '경기도', '2021-04-02 12:00', 223, '치킨')
(1886, '경기도', '2021-04-02 13:00', 247, '치킨')
(1887, '경기도', '2021-04-02 14:00', 247, '치킨')
(1888, '경기도', '2021-04-02 15:00', 285, '치킨')
(1889, '경기도', '2021-04-02 16:00', 429, '치킨')
(1890, '경기도', '2021-04-02 17:00', 872, '치킨')
(1891, '경기도', '2021-04-02 18:00', 1529, '치킨')
(1892, '경기도', '2021-04-02 19:00', 1546, '치킨')
(1893, '경기도', '2021-04-02 20:00', 1252, '치킨')
(1894, '경기도', '2021-04-02 21:00', 1005, '치킨')
(1895, '경기도', '2021-04-02 22:00', 874, '치킨')
(1896, '경기도', '2021-04-02 23:00', 550, '치킨')
(1897, '경기도', '2021-04-03 00:00', 354, '치킨')
(1898, '경기도', '2021-04-03 01:00', 173, '치킨')
(1899, '경기도', '2021-04-03 02:00', 64, '치킨')
(1900, '경기도', '2021-04-03 03:00', 20, '치킨')
(1901, '경기도', '2021-04-03 04:00', 14, '치킨')
(1902, '경기도', '2021-04-03 05:00', 13, '치킨')
(1903, '경기도', '2021-04-03 06:00', 10, '치킨')
(1904, '경기도', '2021-04-03 07:00', 8, '치킨')
(1905, '경기도', '2021-04-03 08:00', 9, '치킨')
(1906, '경기도', '2021-04-03 09:00', 11, '치킨')
(1907, '경기도', '2021-04-03 10:00', 18, '치킨')
(1908, '경기도', '2021-04-03 11:00', 136, '치킨')
(1909, '경기도', '2021-04-03 12:00', 340, '치킨')
(1910, '경기도', '2021-04-03 13:00', 371, '치킨')
(1911, '경기도', '2021-04-03 14:00', 379, '치킨')
(1912, '경기도', '2021-04-03 15:00', 437, '치킨')
(1913, '경기도', '2021-04-03 16:00', 639, '치킨')
(1914, '경기도', '2021-04-03 17:00', 1296, '치킨')
(1915, '경기도', '2021-04-03 18:00', 2350, '치킨')
(1916, '경기도', '2021-04-03 19:00', 2457, '치킨')
(1917, '경기도', '2021-04-03 20:00', 1828, '치킨')
(1918, '경기도', '2021-04-03 21:00', 1564, '치킨')
(1919, '경기도', '2021-04-03 22:00', 1316, '치킨')
(1920, '경기도', '2021-04-03 23:00', 860, '치킨')
(1921, '경기도', '2021-04-04 00:00', 306, '치킨')
(1922, '경기도', '2021-04-04 01:00', 153, '치킨')
(1923, '경기도', '2021-04-04 02:00', 59, '치킨')
(1924, '경기도', '2021-04-04 03:00', 19, '치킨')
(1925, '경기도', '2021-04-04 04:00', 13, '치킨')
(1926, '경기도', '2021-04-04 05:00', 12, '치킨')
(1927, '경기도', '2021-04-04 06:00', 10, '치킨')
(1928, '경기도', '2021-04-04 07:00', 7, '치킨')
(1929, '경기도', '2021-04-04 08:00', 8, '치킨')
(1930, '경기도', '2021-04-04 09:00', 9, '치킨')
(1931, '경기도', '2021-04-04 10:00', 14, '치킨')
(1932, '경기도', '2021-04-04 11:00', 103, '치킨')
(1933, '경기도', '2021-04-04 12:00', 243, '치킨')
(1934, '경기도', '2021-04-04 13:00', 251, '치킨')
(1935, '경기도', '2021-04-04 14:00', 246, '치킨')
(1936, '경기도', '2021-04-04 15:00', 279, '치킨')
(1937, '경기도', '2021-04-04 16:00', 439, '치킨')
(1938, '경기도', '2021-04-04 17:00', 859, '치킨')
(1939, '경기도', '2021-04-04 18:00', 1480, '치킨')
(1940, '경기도', '2021-04-04 19:00', 1570, '치킨')
(1941, '경기도', '2021-04-04 20:00', 1294, '치킨')
(1942, '경기도', '2021-04-04 21:00', 1074, '치킨')
(1943, '경기도', '2021-04-04 22:00', 857, '치킨')
(1944, '경기도', '2021-04-04 23:00', 567, '치킨')
(1945, '경기도', '2021-04-05 00:00', 231, '치킨')
(1946, '경기도', '2021-04-05 01:00', 122, '치킨')
(1947, '경기도', '2021-04-05 02:00', 45, '치킨')
(1948, '경기도', '2021-04-05 03:00', 14, '치킨')
(1949, '경기도', '2021-04-05 04:00', 10, '치킨')
(1950, '경기도', '2021-04-05 05:00', 9, '치킨')
(1951, '경기도', '2021-04-05 06:00', 8, '치킨')
(1952, '경기도', '2021-04-05 07:00', 6, '치킨')
(1953, '경기도', '2021-04-05 08:00', 6, '치킨')
(1954, '경기도', '2021-04-05 09:00', 7, '치킨')
(1955, '경기도', '2021-04-05 10:00', 10, '치킨')
(1956, '경기도', '2021-04-05 11:00', 76, '치킨')
(1957, '경기도', '2021-04-05 12:00', 177, '치킨')
(1958, '경기도', '2021-04-05 13:00', 190, '치킨')
(1959, '경기도', '2021-04-05 14:00', 190, '치킨')
(1960, '경기도', '2021-04-05 15:00', 215, '치킨')
(1961, '경기도', '2021-04-05 16:00', 326, '치킨')
(1962, '경기도', '2021-04-05 17:00', 662, '치킨')
(1963, '경기도', '2021-04-05 18:00', 1180, '치킨')
(1964, '경기도', '2021-04-05 19:00', 1285, '치킨')
(1965, '경기도', '2021-04-05 20:00', 1065, '치킨')
(1966, '경기도', '2021-04-05 21:00', 884, '치킨')
(1967, '경기도', '2021-04-05 22:00', 699, '치킨')
(1968, '경기도', '2021-04-05 23:00', 465, '치킨')
(1969, '경기도', '2021-04-06 00:00', 331, '치킨')
(1970, '경기도', '2021-04-06 01:00', 178, '치킨')
(1971, '경기도', '2021-04-06 02:00', 62, '치킨')
(1972, '경기도', '2021-04-06 03:00', 20, '치킨')
(1973, '경기도', '2021-04-06 04:00', 14, '치킨')
(1974, '경기도', '2021-04-06 05:00', 13, '치킨')
(1975, '경기도', '2021-04-06 06:00', 10, '치킨')
(1976, '경기도', '2021-04-06 07:00', 9, '치킨')
(1977, '경기도', '2021-04-06 08:00', 9, '치킨')
(1978, '경기도', '2021-04-06 09:00', 10, '치킨')
(1979, '경기도', '2021-04-06 10:00', 14, '치킨')
(1980, '경기도', '2021-04-06 11:00', 105, '치킨')
(1981, '경기도', '2021-04-06 12:00', 237, '치킨')
(1982, '경기도', '2021-04-06 13:00', 255, '치킨')
(1983, '경기도', '2021-04-06 14:00', 256, '치킨')

In [14]:
def select_main_table():
    '''
    index 화면에 들어갈 각 시도별/업종별 최신 배달 주문건수를 조회하는 테이블
    '''
    model_list = ['chicken', 'ilsik', 'bunsik', 'yasik', 'jokbal', 'jungsik', 'jimtang', 'cafe', 'fastfood', 'hansik', 'etc']

    result = pd.DataFrame(columns=['광역시도명', '시간', '주문건수', '업종명'])

    with sqlite3.connect('./db.sqlite3') as conn:
        cur = conn.cursor()
        i = 0

        for model in model_list:

            query = "SELECT * FROM main_" + str(model) + " ORDER BY time DESC LIMIT 2;"
            cur.execute(query)
            rows = cur.fetchall()

            for row in rows:
                result.loc[i] = row[1:]
                i += 1

        cur.close()
    conn.close()

#     result = result.sort_values(by='주문건수', ascending=False).reset_index(drop=True)

    result = result[['시간', '광역시도명', '업종명', '주문건수']]
    return result.to_dict('records')

In [15]:
select_main_table()

[{'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '치킨', '주문건수': 713},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '치킨', '주문건수': 91},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '돈까스/일식', '주문건수': 142},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '돈까스/일식', '주문건수': 9},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '분식', '주문건수': 131},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '분식', '주문건수': 9},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '야식', '주문건수': 143},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '야식', '주문건수': 22},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '족발/보쌈', '주문건수': 112},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '족발/보쌈', '주문건수': 17},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '중식', '주문건수': 181},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '중식', '주문건수': 7},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '찜/탕', '주문건수': 37},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '찜/탕', '주문건수': 2},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '카페/디저트', '주문건수': 100},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '카페/디저트', '주문건수': 5},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '패스트푸드', '주문건수': 131},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '패스트푸드', '주문건수': 31},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '한식', '주문건수': 182},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '한식', '주문건수': 11},
 {'시간': '2021-04-19 23:00', '광역시도명': '경기도', '업종명': '기타', '주문건수': 79},
 {'시간': '2021-04-19 23:00', '광역시도명': '서울', '업종명': '기타', '주문건수': 8}]

In [280]:
# 테이블 데이터 삭제

conn = sqlite3.connect('./db.sqlite3')
cur = conn.cursor()

query =  '''DELETE FROM main_etc '''

cur.execute(query)
conn.commit()
    
cur.close()
conn.close()

In [7]:
import pandas as pd
import numpy as np

In [8]:
def select_all(table=None):
    conn = sqlite3.connect('./db.sqlite3')
    cur = conn.cursor()

    query = "SELECT * FROM main_" + str(table)

    cur.execute(query)

    rows = cur.fetchall()

    cur.close()
    conn.close()
    
    result = pd.DataFrame(rows, columns=['index', '광역시도명', '시간', '주문건수', '업종명']).sort_values(by='시간', ascending=False)
    result = result.iloc[:, 1:]

    return result

In [16]:
select_all('chicken')

     광역시도명                시간  주문건수 업종명
1535    서울  2021-04-19 23:00    91  치킨
767    경기도  2021-04-19 23:00   713  치킨
766    경기도  2021-04-19 22:00  1049  치킨
1534    서울  2021-04-19 22:00   136  치킨
765    경기도  2021-04-19 21:00  1301  치킨
...    ...               ...   ...  ..
770     서울  2021-03-19 02:00     9  치킨
769     서울  2021-03-19 01:00    28  치킨
1      경기도  2021-03-19 01:00   208  치킨
0      경기도  2021-03-19 00:00   423  치킨
768     서울  2021-03-19 00:00    53  치킨

[1536 rows x 4 columns]

In [18]:
def add_datetime_column(df):
    df['시간'] = pd.to_datetime(df['시간'])

    df['year'] = df['시간'].dt.year
    df['month'] = df['시간'].dt.month
    df['day'] = df['시간'].dt.day

    return df

In [136]:
def select_main_table():
    '''
    index 화면에 들어갈 각 시도별/업종별 최신 배달 주문건수를 조회하는 테이블
    '''
    model_list = ['chicken', 'ilsik', 'bunsik', 'yasik', 'jokbal', 'jungsik', 'jimtang', 'cafe', 'fastfood', 'hansik', 'etc']

    result = pd.DataFrame(columns=['광역시도명', '시간', '주문건수', '업종명'])

    with sqlite3.connect('./db.sqlite3') as conn:
        cur = conn.cursor()
        i = 0

        for model in model_list:

            query = "SELECT * FROM main_" + str(model) + " ORDER BY time DESC LIMIT 2;"
            cur.execute(query)
            rows = cur.fetchall()

            for row in rows:
                result.loc[i] = row[1:]
                i += 1

        cur.close()
    conn.close()

    result = result.sort_values(by='주문건수', ascending=False).reset_index(drop=True)

    result = result[['시간', '광역시도명', '업종명', '주문건수']]
    return result.to_dict('records')

In [141]:
model_list = ['chicken', 'ilsik', 'bunsik', 'yasik', 'jokbal', 'jungsik', 'jimtang', 'cafe', 'fastfood', 'hansik', 'etc']

result = pd.DataFrame(columns=['광역시도명', '시간', '주문건수', '업종명'])

for model in model_list:
    
    model_result = select_all(model).reset_index(drop=True)
    
    result = pd.concat([result, model_result], axis=0)

In [165]:
tt = add_datetime_column(result)
# preprocessing_df(tt, formula='일자별')
s = tt.loc[(tt['year'] == max(tt['year'])) & (tt['month'] == max(tt['month']))].reset_index(drop=True)
s['주문건수'] = s['주문건수'].astype('int')

s.groupby(['year', 'month', 'day']).mean()

s.groupby(['업종명']).agg({'주문건수': sum})

         주문건수
업종명
기타      77399
돈까스일식  103071
분식     153411
야식      51309
족발보쌈    89111
중식     211929
찜탕      61924
치킨     308313
카페디저트  169393
패스트푸드  144511
한식     204288

In [189]:


def main_line_data():

    model_list = ['chicken', 'ilsik', 'bunsik', 'yasik', 'jokbal', 'jungsik', 'jimtang', 'cafe', 'fastfood', 'hansik', 'etc']

    result = pd.DataFrame(columns=['광역시도명', '시간', '주문건수', '업종명'])

    for model in model_list:

        model_result = select_all(model).reset_index(drop=True)

        result = pd.concat([result, model_result], axis=0)

    add_result = add_datetime_column(result)

    main_result = add_result.loc[(add_result['year'] == max(add_result['year'])) & (add_result['month'] == max(add_result['month']))].reset_index(drop=True)

    main_result['주문건수'] = main_result['주문건수'].astype('int')

    line_result = main_result.groupby(['year', 'month', 'day']).sum().reset_index()
    line_result[['year', 'month', 'day']] = line_result[['year', 'month', 'day']].astype('str')
    line_result['시간'] = line_result['year'] + '-' + line_result['month'] + '-' + line_result['day']
    line_result['시간'] = pd.to_datetime(line_result['시간']).dt.strftime('%Y-%m-%d')
    line_result.drop(['year', 'month', 'day'], axis=1, inplace=True)
    line_result = line_result[['시간', '주문건수']]
    line_result['주문건수'] = line_result['주문건수'].astype('int')
    
    line_lbl, line_val = divide_df(line_result)
    
    return line_lbl, line_val

In [307]:


def main_pie_data():

    model_list = ['chicken', 'ilsik', 'bunsik', 'yasik', 'jokbal', 'jungsik', 'jimtang', 'cafe', 'fastfood', 'hansik', 'etc']

    result = pd.DataFrame(columns=['광역시도명', '시간', '주문건수', '업종명'])

    for model in model_list:

        model_result = select_all(model).reset_index(drop=True)

        result = pd.concat([result, model_result], axis=0)

    add_result = add_datetime_column(result)

    main_result = add_result.loc[(add_result['year'] == max(add_result['year'])) & (add_result['month'] == max(add_result['month']))].reset_index(drop=True)

    main_result['주문건수'] = main_result['주문건수'].astype('int')

    pie_result = main_result.groupby(['업종명']).agg({'주문건수': sum}).sort_values(by='주문건수', ascending=False)

    pie_data = np.around((pie_result / pie_result.sum() * 100), 2)
    
    
    return pie_data.index.tolist(), pie_data.values.reshape(1, -1)

In [308]:
main_pie_data()

(['치킨', '중식', '한식', '카페디저트', '분식', '패스트푸드', '돈까스일식', '족발보쌈', '기타', '찜탕', '야식'],
 array([[19.65, 13.49, 13.  , 10.77,  9.75,  9.18,  6.53,  5.64,  4.89,
          3.9 ,  3.22]]))

In [157]:
def preprocessing_df(df, formula=None):
    
    if formula == '일자별':

        tmp_df = df.loc[(df['year'] == max(df['year'])) & (df['month'] == max(df['month']))].reset_index(drop=True)
        tmp_df['주문건수'] = tmp_df['주문건수'].astype('int')
        groupby_df = np.round(tmp_df.groupby(['광역시도명', 'year', 'month', 'day']).mean(), 0)
        groupby_df['주문건수'] = groupby_df['주문건수'].astype('int')

        result = groupby_df.reset_index()

        result[['year', 'month', 'day']] = result[['year', 'month', 'day']].astype('str')

        result['시간'] = result['year'] + '-' + result['month'] + '-' + result['day']

        result['시간'] = pd.to_datetime(result['시간']).dt.strftime('%Y-%m-%d')
        result.drop(['year', 'month', 'day'], axis=1, inplace=True)

        result = result[['광역시도명', '시간', '주문건수']]

    elif formula == '시간대별':

        tmp_df = df.sort_values('시간', ascending=False)[:48]

        result = tmp_df.groupby(['광역시도명', '시간']).agg({'주문건수': sum}).reset_index()

        result['시간'] = pd.to_datetime(result['시간']).dt.strftime('%Y-%m-%d-%H') + '시'

    return result

In [23]:
def cutting_area(df, cut_column):
    
    tmp = df.loc[df['광역시도명'] == cut_column].reset_index(drop=True)
    tmp.drop('광역시도명', axis=1, inplace=True)

    return tmp

In [26]:
def divide_df(df):
    table1 = df['시간'].values
    table2 = df['주문건수'].values

    return table1.tolist(), table2.tolist()

In [32]:

def execute_all(table, formula):
    
    table = select_all(table)

    add_column_tbl = add_datetime_column(table)
    daily_tbl = preprocessing_df(add_column_tbl, formula='일자별')
    hour_tbl = preprocessing_df(add_column_tbl, formula='시간대별')
    
    sl_daily_tbl = cutting_area(daily_tbl, '서울')
    gg_daily_tbl = cutting_area(daily_tbl, '경기도')
    
    sl_hour_tbl = cutting_area(hour_tbl, '서울')
    gg_hour_tbl = cutting_area(hour_tbl, '경기도')
    
    if formula == '일자별':
        sl_daily_lbl, sl_daily_val = divide_df(sl_daily_tbl)
        gg_daily_lbl, gg_daily_val = divide_df(gg_daily_tbl)
        return sl_daily_lbl, sl_daily_val, gg_daily_lbl, gg_daily_val
    
    elif formula =='시간대별':
        sl_hour_lbl, sl_hour_val = divide_df(sl_hour_tbl)
        gg_hour_lbl, gg_hour_val = divide_df(gg_hour_tbl)
        return sl_hour_lbl, sl_hour_val, gg_hour_lbl, gg_hour_val

In [52]:
# 테이블 데이터 삭제

conn = sqlite3.connect('./db.sqlite3')
cur = conn.cursor()

query =  '''DELETE FROM main_etc '''

cur.execute(query)
conn.commit()
    
cur.close()
conn.close()

In [18]:
import sqlite3
values = [['서울', '2021-03-21 00:00', '30']]


with sqlite3.connect('./db.sqlite3') as conn:
    cur = conn.cursor()
    query = "insert into main_chicken(area_name, time, predict) values(?, ?, ?)"
    cur.executemany(query, values)
    conn.commit()

In [1]:
import pandas as pd
import numpy as np

In [35]:
predict_raw = pd.read_csv('../data_analysis/predict/data/predict_final.csv', encoding='utf-8', index_col=0)
predict_raw

,광역시도명,기온,풍속,습도,PM10,운량,강수량,확진자수,day_금,day_목,...,holiday_1,holiday_2,holiday2_0,holiday2_1,climate_1,climate_2,climate_3,climate_4,rain_snow_0,rain_snow_1
0,서울,12.50,0.80,47.0,116.240,9.0,0.0,118,1,0,...,0,0,1,0,0,0,0,1,1,0
1,서울,12.40,1.70,49.0,114.400,9.0,0.0,118,1,0,...,0,0,1,0,0,0,0,1,1,0
2,서울,12.50,2.40,52.0,97.360,10.0,0.0,118,1,0,...,0,0,1,0,0,0,0,1,1,0
3,서울,12.40,2.60,55.0,96.800,10.0,0.0,118,1,0,...,0,0,1,0,0,0,0,1,1,0
4,서울,12.20,1.80,55.0,90.640,10.0,0.0,118,1,0,...,0,0,1,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1531,경기도,15.08,2.42,55.8,68.578,0.0,0.0,180,0,0,...,0,0,1,0,1,0,0,0,1,0
1532,경기도,13.62,2.04,62.0,67.990,0.0,0.0,180,0,0,...,0,0,1,0,1,0,0,0,1,0
1533,경기도,12.50,1.80,65.4,66.196,1.0,0.0,180,0,0,...,0,0,1,0,1,0,0,0,1,0
1534,경기도,11.36,1.58,71.4,64.941,0.0,0.0,180,0,0,...,0,0,1,0,1,0,0,0,1,0
1535,경기도,10.34,1.12,76.2,63.078,1.6,0.0,180,0,0,...,0,0,1,0,1,0,0,0,1,0

In [47]:
basic_data = pd.DataFrame(pd.date_range('2021-03-19', '2021-04-20', freq='H'), columns=['날짜'])
basic_data = basic_data.iloc[:-1]
basic_data['날짜'] = basic_data['날짜'].dt.strftime('%Y-%m-%d %H:%M')
basic_data

                   날짜
0    2021-03-19 00:00
1    2021-03-19 01:00
2    2021-03-19 02:00
3    2021-03-19 03:00
4    2021-03-19 04:00
..                ...
763  2021-04-19 19:00
764  2021-04-19 20:00
765  2021-04-19 21:00
766  2021-04-19 22:00
767  2021-04-19 23:00

[768 rows x 1 columns]

In [64]:
import sqlite3

def insert_db(table, values):
    with sqlite3.connect('./db.sqlite3') as conn:
        cur = conn.cursor()
        query = "insert into " +str(table) + "(time, area_name, predict, category) values(?, ?, ?, ?)"
        cur.executemany(query, values)
        conn.commit()
    cur.close()
    conn.close()

In [281]:
import os
import fnmatch
import joblib
from sklearn.linear_model import Ridge

area_list = ['서울', '경기도']
model_dic = {'치킨': 'chicken', '돈까스일식': 'ilsik', '분식': 'bunsik','야식': 'yasik', 
             '족발보쌈': 'jokbal', '중식': 'jungsik', '찜탕': 'jimtang',
             '카페디저트': 'cafe', '패스트푸드': 'fastfood', '한식': 'hansik', '기타': 'etc'}


model_base_path = '../data_analysis/model/'

for file_list in os.listdir(model_base_path): 
    
    for area in area_list:
    
        search_name = area+'*.pkl'
        
        if fnmatch.fnmatch(file_list, search_name):

            basic_data = pd.DataFrame(pd.date_range('2021-03-19', '2021-04-20', freq='H'), columns=['날짜'])
            basic_data = basic_data.iloc[:-1]
            basic_data['날짜'] = basic_data['날짜'].dt.strftime('%Y-%m-%d %H:%M')
            basic_data['광역시도명'] = area
            
            file_split = file_list.split('_')

            model_path = model_base_path + file_list
            loaded_model = joblib.load(model_path)

            X_predict = predict_raw.loc[predict_raw['광역시도명']==area].reset_index(drop=True)
            X_predict.drop('광역시도명', axis=1, inplace=True)
            
            preds = loaded_model.predict(X_predict.values)
            
            basic_data['예측값'] = np.round(np.expm1(preds), 0)
            basic_data['예측값'] = basic_data['예측값'].astype('int')
            basic_data['업종명'] = file_split[1] 
            
            table_name = 'main_' + model_dic[file_split[1]]
            insert_db(table_name, basic_data.values.tolist())

In [245]:
import os
import fnmatch
import joblib

loaded_model = joblib.load('../data_analysis/model/경기도_야식_ridge.pkl')
lm2 = joblib.load('../data_analysis/model/경기도_중식_ridge.pkl')

In [246]:
predict = predict_raw.loc[predict_raw['광역시도명']=='경기도'].drop('광역시도명', axis=1).values

In [250]:
pred = loaded_model.predict(predict)[:10]
pred2 = lm2.predict(predict)[:10]
np.exp(pred)
# np.round(np.exp(pred), 0)

array([100.72209657,  55.34043489,  32.23256617,  18.0999967 ,
        16.08772574,   9.6620756 ,   8.78885634,   8.70733286,
         7.76283259,   7.51072276])

In [73]:
basic_data = pd.DataFrame(pd.date_range('2021-03-19', '2021-04-20', freq='H'), columns=['날짜'])
basic_data = basic_data.iloc[:-1]
basic_data['날짜'] = basic_data['날짜'].dt.strftime('%Y-%m-%d %H:%M')
basic_data['광역시도명'] = area
basic_data

                   날짜 광역시도명
0    2021-03-19 00:00   경기도
1    2021-03-19 01:00   경기도
2    2021-03-19 02:00   경기도
3    2021-03-19 03:00   경기도
4    2021-03-19 04:00   경기도
..                ...   ...
763  2021-04-19 19:00   경기도
764  2021-04-19 20:00   경기도
765  2021-04-19 21:00   경기도
766  2021-04-19 22:00   경기도
767  2021-04-19 23:00   경기도

[768 rows x 2 columns]

In [74]:
file_split

['서울', '한식', 'ridge.pkl']

In [75]:
model_path

'../data_analysis/model/서울_한식_ridge.pkl'

In [251]:
lm2()

Ridge(alpha=0.01)